version: "2"

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_build:
    - conda env export --from-history
    - echo "print(\"hi\")" > ./test.py
    - echo "from vapor import animation" > ./test.py
    - python ./test.py

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: environment.yml
