version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    conda: "latest"

  commands:
    - echo "from vapor import animation" > test.py
    - python test.py

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: environment.yml
