version: "2"

conda:
  environment: environment.yml

build:
  image: latest
  jobs:
    post_build:
    - conda env export --from-history
    - python -c "print(\"hi\")"
    - python -c "import matplotlib"
    - python -c "from vapor import animation"
    #- echo "print(\"hi\")" > ./test.py
    #- echo "from vapor import animation" > ./test.py
    #- python ./test.py

python:
  version: 3.9
  install:
    - method: pip
      path: .

submodules:
    include: all
