version: "2"

  #apt_packages:
  #  - 
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_build:
    #- conda env export --from-history
    #- python -c "print(\"hi?\")"
    #- python -c "help(\"modules\")"
    #- python -c "import matplotlib"
    #- printenv
    #- conda list
    #- conda env list
    #- gcc --version
    #- ls /home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest
    #- ls $CONDA_ENVS_PATH/latest/lib/python3.9/site-packages
    - cp $READTHEDOCS_REPOSITORY_PATH/config.py $CONDA_ENVS_PATH/latest/lib/python3.9/site-packages/vapor
    #- ls $CONDA_ENVS_PATH/latest/include
    #- ls /home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest
    #- ls /home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest/lib
    #- ls /home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest/lib/python3.9/site-packages/vapor
    #- ls /opt/micromamba/envs/build/conda-bld/vapor_1724092900864/work
    #- ls /opt/micromamba/envs/build/conda-bld/vapor_1724092900864/work/lib/osgl
    #- ls /opt/micromamba/envs/build/conda-bld/vapor_1724092900864/work/lib/osgl/glad
    #- ls /opt/micromamba/envs/build/conda-bld/vapor_1724092900864/work/build
    #- python -c "/home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest/lib/python3.9/site-packages/vapor include
    #- ls /home/docs/checkouts/readthedocs.org/user_builds/rtd-test2025/conda/latest/lib/python3.9/site-packages/vapor/include
    - python -c "from vapor import animation"
    #- echo "print(\"hi\")" > ./test.py
    #- echo "from vapor import animation" > ./test.py
    #- python ./test.py

#python:
#  install:
#    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: environment.yml
